### ISSUE TITLE
Make journald support optional

### ISSUE THREAD

**Issue by spbnick** [Scribery/tlog#100]
To support working on distros which don't use systemd/journald, consider supporting building without them.

**Comment by trevor-vaughan** [comment]
This is very much needed for systems still using EL6 and distros without journald.

**Comment by spbnick** [comment]
@trevor-vaughan, thank you, yes, that is our primary concern.

**Comment by spbnick** [comment]
Implemented with c833a8598ddf6de506c2b55a0bc5ad08d5f0e9a6.
