### ISSUE TITLE
Return value of function tlog_pkt_pos_move_past

### ISSUE THREAD

**Issue by danghai** [Scribery/tlog#144]
I see the function `tlog_pkt_pos_move_past` returning `void` : 
https://github.com/danghai/tlog/blob/master/lib/pkt.c#L270
However, I see you put the if condition in tlog-play.
https://github.com/danghai/tlog/blob/master/src/tlog-play.c#L800 .

I also have question about `tlog_pkt_pos_move`.  Does this function use to move position (forward) after you reading the packet? And you will use the function` tlog_pkt_pos_move_past` to move position (backward)? I see the `ssize_t off` using as offset to move, but I do not see you use this variable for function `tlog_pkt_post_move_past`. Can you help me clarify it?

**Comment by spbnick** [comment]
Regarding first question: these code pieces use two different functions: `tlog_pkt_pos_move_past` and `tlog_pkt_pos_is_past`. The first one is for moving the position, the second one is for checking it.

Regarding second question: the code uses `tlog_pkt_pos_move` after a packet has been read, and during writing it, to move a position by specific amounts and to track the writing position. E.g. once the packet is read, the code starts writing it. After it manages to write a piece of a packet, it moves the writing position by the size of the piece that was written, thus marking it "written" in a way.

The code uses `tlog_pkt_pos_move_past` to move the position past the end of the packet, essentially marking it as fully-written for the writing code. It doesn't need to know by how much the position needs to move, it just always moves it to right after the packet content, so it doesn't need the `off` argument.

**Comment by spbnick** [comment]
Closing as there doesn't seem to be an issue here. Please reopen if there is still a problem.
