### ISSUE TITLE
Implement passing the shell name to tlog-rec via argv[0]

### ISSUE THREAD

**Issue by spbnick** [Scribery/tlog#16]
The simplest way to specify the shell to tlog-rec might be specifying a special shell for the user - one for each possible invoked shell. Such shell might start with "tlog-rec-shell-" and end with the shell name. E.g. "tlog-rec-shell-bash". The actual executable would be just a symlink to tlog-rec and tlog-rec would extract the shell to be invoked from argv[0]. This would make standalone setups easier to implement and wouldn't require using pam_env or pam_sss to pass the shell to tlog-rec via environment variables.

**Comment by paulohrpinheiro** [comment]
I have done some tests, and to function exactly as described, a *GLIBC* function, `execvp`, must be used, which, given a program with an incomplete PATH, performs a search, usually on `/bin` and `/usr/bin`. On the man page it says:

> This confstr (3) call typically returns the value "/bin: /usr/bin".

We can, through a `#ifdef _GNU_SOURCE` or through *autoconf*, do the verification, and implement this logic as a callback.

There is also the option of simply requiring the link to be made to the full path, for example, `tlog-rec-shell-bin-bash`. What do you think?

**Comment by spbnick** [comment]
I thought about this for a while, and I think it is better to encode the full shell path in the symlink. For most cases the path will be short and obvious. We will have to provide a way to encode actual dashes, but it will still be more straight-forward and obvious than relying on PATH, which needs to be specified elsewhere.

To implement dash encoding we can use basic backslash escaping rule: any character following a backslash would be interpreted literally, with backslash dropped, while a dash without a preceding backslash would be interpreted as a forward slash.

**Comment by paulohrpinheiro** [comment]
And if we find out the real name of the program (where the link points), and from there get the rest of the string and work. Then we could have something like `tlog-rec-bin-bash` or `tlog-rec-usr-local-bin-bash`, and use, respectively, `/bin/bash` and `/usr/local/bin/bash`.

I believe that this is less error-prone when creating the link. But these two options solve the problem.

**Comment by spbnick** [comment]
Yeah, only I think we need to keep "-shell" in there.
So, let me provide a few examples, so that everything is clear to both of us.

    /usr/bin/tlog-rec-shell-bin-bash -> /usr/bin/tlog-rec               # tlog-rec will invoke /bin/bash
    /usr/bin/tlog-rec-shell-usr-local-bin-bash -> /usr/bin/tlog-rec     # tlog-rec will invoke /usr/local/bin/bash
    /usr/bin/tlog-rec-shell-bin-weird\-shell -> /usr/bin/tlog-rec       # tlog-rec will invoke /bin/weird-shell

Are we talking about the same thing?

**Comment by paulohrpinheiro** [comment]
Now I understood what you explained. Can I get this issue?

**Comment by spbnick** [comment]
Sure!

Another thing, we need to do with this, though, is to install symlinks to several popular shells. Those should probably be `sh`, `bash`, `ksh`, `tcsh`, `zsh`, and `fish`, but please correct me if I'm wrong.
We need to check that those symlinks would work on both Debian- and Red Hat-based distros, at least.
And  then both the `make install` and the RPM package should install them.

**Comment by paulohrpinheiro** [comment]
The only ones I remember now are ash and dash. I'll take a look at the LSB documents.

**Comment by spbnick** [comment]
Hi @paulohrpinheiro, do you have any progress on this? Do you need any help?

**Comment by paulohrpinheiro** [comment]
Hello @spbnick. All right? I apologize for not talking to you, but I'm still busy with my work, but from here a week ago I'll be able to return and resolve that issue. Once again, I'm sorry, and thanks for asking.

**Comment by spbnick** [comment]
Sure, no problem, @paulohrpinheiro. I just need to do some planning. I'd like to have this done before [my FOSDEM presentation](https://fosdem.org/2017/schedule/event/session_recording/), and if I have time perhaps I'll do it myself, but don't worry, there will still be plenty of interesting things to do for you :)

**Comment by paulohrpinheiro** [comment]
If you wait for me, you'll be very close to the presentation, so it's
safer for you to do it. And from what I've seen of the various issues,
there's a lot of fun to do. And good luck in your presentation!

--
Paulo Henrique Rodrigues Pinheiro
paulohrpinheiro@gmail.com
https://paulohrpinheiro.xyz

Em 23-01-2017 10:36, Nikolai Kondrashov escreveu:

**Comment by spbnick** [comment]
Thanks, @paulohrpinheiro!
