### ISSUE TITLE
Support dumping loaded configuration

### ISSUE THREAD

**Issue by spbnick** [Scribery/tlog#160]
For debugging and integration with configuration UIs it would be useful to implement dumping loaded configuration in all `tlog-*` programs. One way to do it could be adding a command-line option accepting the (optional) configuration origin range (see `m4/tlog/conf_origin.m4`) to output the configuration for.

**Comment by justin-stephenson** [comment]
Hello @spbnick - Is this issue already fixed in commit fc8134b1f77bcb73e011a13879880c69bcd74c3f ?

**Comment by justin-stephenson** [comment]
Closing as this is completed.
