### ISSUE TITLE
Add RPM build to CI runs

### ISSUE THREAD

**Issue by spbnick** [Scribery/tlog#168]

**Comment by danghai** [comment]
Hi Nick, I add RPM build to CI runs, but it has the problem about directory. It produces the error when I try to build with RPM:  
```
RPM build errors:
    File must begin with "/": %{_tmpfilesdir}/tlog.conf
```

Could you review this commit these change in `.travis.yml`: https://github.com/danghai/tlog/commit/b214ffded7ce5d002a732d0567138fcad9ac420a

Thanks

**Comment by spbnick** [comment]
Looks good, good job figuring out rpmbuild! Please submit a PR and let's take it from there.
