### ISSUE TITLE
Implement recording throttling

### ISSUE THREAD

**Issue by spbnick** [Scribery/tlog#17]
It should be possible to limit tlog recording throughput so that neither local nor remote systems are overwhelmed with too many log messages and don't run out of space. The best way would be to have the logging server implement per-process rate limiting with flow control, i.e. without dropping the log messages. However, as the existing logging servers don't seem to do that, we'll need to implement that in tlog. The limit might be expressed in encoded bytes per second and observed at the writer level.

**Comment by trevor-vaughan** [comment]
@spbnick As a corollary to this, you're going to want to throttle tlog recording on "non-human" console output.

For instance, if I `cat /dev/urandom` (or read a man page) I really don't want to audit any of that.

In my fork of the `sudosh2` project, we implemented this type of configurable throttling based on research into human typing speeds.

Look at the lines containing `SECONDS_THROTTLE` here https://github.com/onyxpoint/sudosh2/blob/master/src/sudosh.c.

**Comment by spbnick** [comment]
Ooooh, that's very interesting, thanks a lot, @trevor-vaughan! I'll definitely take a look at this feature, as well as the whole of sudosh2, when I start working on this issue.

**Comment by spbnick** [comment]
I implemented rate limiting at the logging level, with either policing (dropping messages) or shaping (throttling, delaying messages). Please reopen this issue if that's unsuitable.
