### ISSUE TITLE
Logging /dev/urandom output terminates with "Operation not supported"

### ISSUE THREAD

**Issue by spbnick** [Scribery/tlog#171]
When `tlog-rec-session` is used to record the output of `cat /dev/urandom` to Journal, it quickly terminates with the following output:

    Operation not supported
    Failed logging terminal data
    Failed transferring TTY data

**Comment by spbnick** [comment]
Actually, the same happens when logging to a file, on Fedora 26 (same as with Journal), but it doesn't happen on Debian Testing. The command reproducing this is:

    tlog-rec -o /dev/null --limit-action=delay cat /dev/urandom

**Comment by spbnick** [comment]
Same on Fedora 25.

**Comment by danghai** [comment]
Hi Nick, 
It works for me when I write to `journal` following command:
`tlog-rec --writer=journal cat /dev/urandom`

**Comment by spbnick** [comment]
Have you tried this on Fedora 25 or 26?

**Comment by danghai** [comment]
I do not try this on Fedora 25 or 26 yet. I will try it.

**Comment by danghai** [comment]
I tried this on Fedora 26. It has error following this command: 
`tlog-rec -w file -o /dev/null --limit-action=delay cat /dev/urandom`

But it does not have error with 3 commands: 
`tlog-rec -w file -o /dev/null cat /dev/urandom`
`tlog-rec -w file -o /dev/null --limit-action=pass cat /dev/urandom`
`tlog-rec -w file -o /dev/null --limit-action=drop cat /dev/urandom`

The issue may come from `limit-rate` action? And I do not know `Operation not supported` string came from?

**Comment by spbnick** [comment]
Good investigation! Yes, it seems that the "delay" rate-limit action is at fault. The "Operation not supported" is an error string for a particular errno value. So, something in the rate-limit JSON writer is failing with errno set to that value. You can lookup the errno code for an error message using the `errno` tool (from `moreutils` package on Debian-based distros), like this:

    errno -s "Operation not supported"

Look at the rate-limit JSON writer in `lib/tlog/rl_json_writer.c` and try to figure it out.

**Comment by mdpi-symfony** [comment]
I still have the same issue on Ubuntu 14.04, works well on 16.04 and 18.04.

When logged in over SSH and using /usr/bin/tlog-rec-session, after running a couple of commands (5 to 10sec), the session is closed with this message:

`No such file or directory
Failed logging terminal data
Failed transferring TTY data
Connection to xxx.yyy.com closed.`

**Comment by spbnick** [comment]
Whoa, would you care to share your `tlog-rec-session.conf`? Thank you.

**Comment by mdpi-symfony** [comment]
```
{
    "log": {
        "input" : false,
        "output" : true,
        "window" : true
    },

    "limit": {
    },

    "file": {
    },

    "syslog": {
    },

    "journal": {
        "priority" : "info",
        "augment" : true
    },

    "writer" : "journal"
}
```

**Comment by mdpi-symfony** [comment]
Thank you @spbnick , new ticket created: https://github.com/Scribery/tlog/issues/221
