### ISSUE TITLE
Failed creating lock file 

### ISSUE THREAD

**Issue by danghai** [Scribery/tlog#182]
Every time I turn on the terminal, it shows the error: Failed creating lock file. 
![fail](https://user-images.githubusercontent.com/10912671/36576466-b3d9098a-1805-11e8-8035-ff91f425851a.JPG)

**Comment by spbnick** [comment]
Read https://github.com/Scribery/tlog#installing regarding session lock directory.

**Comment by danghai** [comment]
I already created `tlog` in /var/run and make it writable (only) for the user(s) tlog-rec-session runs as. But it still has error when I turn on terminal

**Comment by spbnick** [comment]
This is because your session lock directory is configured to be `/usr/var/run/tlog`. Add `--localstatedir=/var` to configure options, and rebuild. Also, it would be good to add it to build instructions in README.md.

**Comment by danghai** [comment]
It still has error when I try to use `--localstatedir=/var` to configure options.  The error is only removed when I use `sudo make uninstall`

**Comment by spbnick** [comment]
You need to figure out which binary is actually executed when the user logged in and whether it has the updated path compiled in, or not.
