### ISSUE TITLE
Message ID is out of order when playing back from elasticsearch

### ISSUE THREAD

**Issue by theblazehen** [Scribery/tlog#184]
```
Message ID is out of order
Failed reading the source at message #1
```
error appears after a short while when using tlog-play with elasticsearch. 

Elasticsearch version: 2.4.6

rsyslog.conf
```
module(load="omelasticsearch")

template(name="tlog" type="list") {
    constant(value="{")
    property(name="timegenerated"
             outname="timestamp"
             format="jsonf"
             dateFormat="rfc3339")
    constant(value=",")
    property(name="msg"
             regex.expression="{\\(.*\\)"
             regex.submatch="1")
    constant(value="\n")
}
if $programname == "tlog" then {
action(type="omelasticsearch"
                name="tlog-elasticsearch"
                server="scriberyxpack"
                serverport="9200"
                searchIndex="tlog-rsyslog"
                searchType="tlog"
                bulkmode="off"
                action.resumeretrycount="-1"
                errorfile="/var/log/omelasticsearch.log"
                template="tlog"
                )
}
```

`tlog-play` command: `tlog-play --lax -r es --es-baseurl=http://scriberyxpack:9200/tlog-rsyslog/tlog/_search --es-query="session:1 AND timestamp:>=now-7d"`

Am I doing something wrong or is this a bug?

**Comment by spbnick** [comment]
This might be a bug, but take a look at what is returned for that query string. You might get documents from two or more recordings in response.

**Comment by spbnick** [comment]
Also, to make sure you get only one recording you can query by `host` and `id`. I understand that session ID might be more useful, but the current audit subsystem implementation makes them unique only within single boot.

**Comment by spbnick** [comment]
Edited the above to use `rec` instead of `id`.

**Comment by theblazehen** [comment]
I ran `curl -XDELETE scriberyxpack:9200/tlog-rsyslog` right before rebooting and logging in as a user that had session logging enabled, and there weren't any other sessions open that could have been recording.

I only have a single host that would be logging. Output of `curl scriberyxpack:9200/tlog-rsyslog/_search | jq .`: https://linx.li/wl7fv2x8.file

It appears that there is also only a single value for `rec`, 
```
# curl -s scriberyxpack:9200/tlog-rsyslog/_search | jq . | grep rec
          "rec": "605389c0ee744fad9de2bd06d08577c6-4f7-11eee",
          "rec": "605389c0ee744fad9de2bd06d08577c6-4f7-11eee",
          "rec": "605389c0ee744fad9de2bd06d08577c6-4f7-11eee",
          "rec": "605389c0ee744fad9de2bd06d08577c6-4f7-11eee",
          "rec": "605389c0ee744fad9de2bd06d08577c6-4f7-11eee",
          "rec": "605389c0ee744fad9de2bd06d08577c6-4f7-11eee",
          "rec": "605389c0ee744fad9de2bd06d08577c6-4f7-11eee",
          "rec": "605389c0ee744fad9de2bd06d08577c6-4f7-11eee",
          "rec": "605389c0ee744fad9de2bd06d08577c6-4f7-11eee",
          "rec": "605389c0ee744fad9de2bd06d08577c6-4f7-11eee",
```

**Comment by spbnick** [comment]
I see that you have documents with the same ID but slightly different timestamps. Could it be that rsyslog is receiving and/or sending them twice?

**Comment by theblazehen** [comment]
Ah, that's right! rsyslog was sending them twice. While trying to get the rsyslog configuration working I had uncommented `$OmitLocalLogging on`, and forgot to comment it back out. (That particular problem with rsyslog was due to selinux restricting network access...).

Thanks for your help!
