### ISSUE TITLE
Is there a HOW-To for using tlog in FreeIPA? 

### ISSUE THREAD

**Issue by MoHD20** [Scribery/tlog#185]

**Comment by spbnick** [comment]
Hi @MoHD20, at the moment we have no support in FreeIPA, only plans to have some. If you use FreeIPA and SSSD, you can use local SSSD configuration to specify what users and groups to record. See [sssd-session-recording(5)](https://www.mankier.com/5/sssd-session-recording). This will give you transparent enabling/disabling of session recording on specific machines, with preserving the user shell.

**Comment by justin-stephenson** [comment]
Closing this one.
