### ISSUE TITLE
The tlog project needs somewhere to collaborate that's not GitHub

### ISSUE THREAD

**Issue by trevor-vaughan** [Scribery/tlog#204]
Slack, Mailing List, whatever. Can't find anything from the home page and have development questions.

If this is the preferred method for all comms and questions, that should probably be added to the website.

**Comment by spbnick** [comment]
Yes, please no Slack. All the heat generated by browsers running Slack contributes to global warming.

**Comment by sabbaka** [comment]
I have fired request to create a mailing list - https://pagure.io/fedora-infrastructure/issue/7372
Sorry, for taking that long time to do this.

**Comment by sabbaka** [comment]
Mailing list was created - scribery-devel@lists.fedoraproject.org

**Comment by justin-stephenson** [comment]
@sabbaka can this Issue be closed now?
