### ISSUE TITLE
Permission denied when using file writer

### ISSUE THREAD

**Issue by fossxplorer** [Scribery/tlog#210]
I was looking into separating log from Tlog into a separate file to avoid spamming journal, but i'm unable to do so. Unless i miss something, it seems we are unable to use the writer type file due to permission issues:
Changes to defaults in /etc/tlog/tlog-rec-session.conf:
"writer" : "file"
"path" : "/var/data/tlog.log"
[root@tlog01 ~]# ll /var/data/tlog.log 
-rw-rw-r--. 1 root root 11887 Sep  3 12:26 /var/data/tlog.log

[root@tlog01 ~]# su tloguser
Locale charset is ANSI_X3.4-1968 (ASCII)
Assuming locale environment is lost and charset is UTF-8
Permission denied
Failed opening log file "/var/data/tlog.log"
Failed creating JSON message writer
Failed creating log sink

I've also tried changing the owner and group to "tlog" without any success. 
It works when others have write access to the log file, but that's not desirable (i.e we don't want the user we are logging to be able to delete the logs).

**Comment by spbnick** [comment]
Hi @fossxplorer, could you please check which user tlog-rec-session is running as, and can it write to that file?

**Comment by fossxplorer** [comment]
Tlog-rec-session when configured with journal writer type runs as the user "tlog" that has write access to the log file when group ownership of the log file is changed to tlog. But still a user is unable to log into due to permission denied:
[root@tlog01 ~]# ll /var/data/tlog.log 
-rw-rw-r--. 1 root root 11959 Sep  4 09:03 /var/data/tlog.log
[root@tlog01 ~]# su tlog -c "echo Text from \$USER >> /var/data/tlog.log"
This account is currently not available.
[root@tlog01 ~]# chsh  -s /bin/bash tlog
Changing shell for tlog.
Shell changed.
[root@tlog01 ~]# su tlog -c "echo Text from \$USER >> /var/data/tlog.log"
bash: /var/data/tlog.log: Permission denied
[root@tlog01 ~]# chgrp tlog /var/data/tlog.log 
[root@tlog01 ~]# su tlog -c "echo Text from \$USER >> /var/data/tlog.log"
[root@tlog01 ~]# tail -n1 /var/data/tlog.log
Text from tlog
[root@tlog01 ~]# su tloguser
Permission denied
Failed opening log file "/var/data/tlog.log"
Failed creating JSON message writer
Failed creating log sink

**Comment by spbnick** [comment]
Thank you for the report and for the extra information, @fossxplorer. I think I forgot to handle this case previously and it should now be fixed in #211. Please test the code in that PR and respond with your results. Thank you.

**Comment by fossxplorer** [comment]
Likewise!  Sure i will test. Do i need to check out https://github.com/spbnick/tlog/commits/open_json_writer_file_with_euid_egid and build it to test?

**Comment by spbnick** [comment]
Great! You can also download it as a zip archive, as well: https://github.com/spbnick/tlog/archive/open_json_writer_file_with_euid_egid.zip

**Comment by fossxplorer** [comment]
Fetched your PR, built an RPM out of it and upgraded the existing Tlog package. Now i'm able to use writer type file and log to a separate file.
Didn't do any extensive testing, but looks very good so far so thanks a billion for your prompt help and fix!

**Comment by spbnick** [comment]
Great, glad it solves your issue! I merged the PR.

**Comment by fossxplorer** [comment]
:thumbsup:
