### ISSUE TITLE
allow tlog-play to send output to a file

### ISSUE THREAD

**Issue by spoore1** [Scribery/tlog#219]
Currently tlog-play requires a terminal connected to the output in order to display the output.  This prevents using normal redirects from sending the playback output to a file.   There are cases where this could be very useful in cases like testing and generating other reports.  

From my point of view either a redirect or an output file option would be enough to provide this feature.  Something like:

tlog-play -i /tmp/recorded_session.tlog > /tmp/recorded_session.out
or
tlog-play -i /tmp/recorded_session.tlog -o /tmp/recorded_session.out

Thanks

**Comment by justin-stephenson** [comment]
This is merged and will be fixed in **v7**
