### ISSUE TITLE
Ubuntu 14.04 - No such file or directory when using tlog-rec-session

### ISSUE THREAD

**Issue by mdpi-symfony** [Scribery/tlog#221]
When logging in over SSH and using /usr/bin/tlog-rec-session, the session is closed with this message:

No such file or directory
Failed logging terminal data
Failed transferring TTY data
Connection to xxx.yyy.com closed.

My config is very basic:

```
{
    "log": {
        "input" : false,
        "output" : true,
        "window" : true
    },

    "limit": {
    },

    "file": {
    },

    "syslog": {
    },

    "journal": {
        "priority" : "info",
        "augment" : true
    },

    "writer" : "journal"
}
```

While trying this: `tlog-rec --writer=journal "aa"`, the same happens:

```
No such file or directory
Failed executing aa

No such file or directory
Failed flushing the log
Failed transferring TTY data
```

**Comment by spbnick** [comment]
Ah, OK. So it fails to even start logging. How did you install tlog?

**Comment by spbnick** [comment]
And which version?

**Comment by spbnick** [comment]
Hmm, that should work OK. I'll need to try it myself. Meanwhile, could you try with the https://github.com/Scribery/tlog/archive/master.zip ?

**Comment by mdpi-symfony** [comment]
I just tried to install it by cloning the git repository: https://github.com/Scribery/tlog.git but still the same issue.

**Comment by mdpi-symfony** [comment]
Same issue by installing from https://github.com/Scribery/tlog/archive/master.zip

**Comment by spbnick** [comment]
I see, thank you. Could you post the strace log?

**Comment by mdpi-symfony** [comment]
strace attached.
[tlog.log](https://github.com/Scribery/tlog/files/2525196/tlog.log)

**Comment by mdpi-symfony** [comment]
Let me know if you would eventually need additional information about the issue.

**Comment by spbnick** [comment]
OK, I tested this myself, and the answer is simple: Ubuntu 14.04 doesn't use systemd nor journal (even though it has libsystemd-journal package). If you would like to use tlog for logging to journal, you'll need to use a version of Ubuntu which has it. Otherwise you'll need to log to syslog or a file.

**Comment by mdpi-symfony** [comment]
Excellent, problem solved by simply installing systemd:

`sudo apt-get install systemd`

Thank you very much. Would be good to implement a better error reporting on tlog-rec-session in order to show which directory is missing. No such file or directory is hard to decode :)

**Comment by spbnick** [comment]
Ah, good to hear. Somehow I got the impression that systemd/journald are not supported on 14.04 at all, and was wrong.

Regarding the error message, we might be able to detect ENOENT from sd_journal_send and report the problem. Submitted #222 for that.
