### ISSUE TITLE
v5 from RHEL8 beta does not exist

### ISSUE THREAD

**Issue by mikedep333** [Scribery/tlog#223]
RHEL8 beta lists tlog as at version 5, but version 5 isn't released yet.
https://access.redhat.com/downloads/content/rhel---8/x86_64/7658/tlog/5-1.el8/x86_64/fd431d51/package

At 1st glance, it seems to be based on fc8134b1f77bcb73e011a13879880c69bcd74c3f from 2018-09-24.

Could you please at least clarify the situation? Perhaps a tag like v5-preview?

**Comment by spbnick** [comment]
@sabbaka, we need to release upstream before making a package otherwise it's confusing. Could you please make sure we have a release of tlog at least before RHEL8 release? I can help.

**Comment by spbnick** [comment]
Thank you for the report, @mikedep333!

**Comment by sabbaka** [comment]
I will do that. @spbnick I'll contact you, thanks. @mikedep333 thanks for the report.

**Comment by mikedep333** [comment]
Thank you guys for tlog!

**Comment by sabbaka** [comment]
@mikedep333 release was done. https://github.com/Scribery/tlog/releases/tag/v5

**Comment by mikedep333** [comment]
@sabbaka Awesome, thank you!
