### ISSUE TITLE
tlog-rec-session Failed logging terminal data

### ISSUE THREAD

**Issue by spoore1** [Scribery/tlog#238]
It seems that when I set the limit rate low and action to delay, I see a failure that causes the users session to be dropped or logged out.  This is happening when the terminal session is flooded with output quickly.

Version is:

tlog-4-4.fc29.x86_64

This is what I have configured:

```
# cat /etc/tlog/tlog-rec-session.conf

{
"writer": "file",
"file": {
"path": "/tmp/test.tlog",
},
"limit": {
"rate": 10,
"action": "delay",
},
}
```

And this is what I'm seeing:

```
[root@fedora-0 tlitest]# ssh tlitestlocaluser1@localhost
tlitestlocaluser1@localhost's password: 
Last login: Mon Mar 25 07:28:13 2019 from ::1

ATTENTION! Your session is being recorded!

[tlitestlocaluser1@fedora-0 ~]$ for num in {0..1000}; do echo "This is a long sentence to type before I attempt to echo out the number that will be printed with it -- $num"; done
This is a long sentence to type before I attempt to echo out the number that will be printed with it -- 0
This is a long sentence to type before I attempt to echo out the number that will be printed with it -- 1
This is a long sentence to type before I attempt to echo out the number that will be printed with it -- 2
...
This is a long sentence to type before I attempt to echo out the number that will be printed with it -- 270

Operation not supported
Failed logging terminal data
Failed transferring TTY data
Connection to localhost closed.

```

**Comment by justin-stephenson** [comment]
When a positive overflow value is reached in tlog_rl_json_writer_write() then clock_nanosleep is returning ENOTSUP:

       ENOTSUP
              The clock_id argument specifies a clock for which clock_nanosleep() is not supported, such as a CPU-time clock.

Looking at the tlog master code this was already fixed in https://github.com/Scribery/tlog/pull/180

@spoore1 Could you check if this problem is resolved in tlog v5?
    https://github.com/Scribery/tlog/releases/tag/v5

**Comment by spoore1** [comment]
It does appear to be working....although very slowly.  But, it hasn't thrown the error yet.  I'll let you know when the test completes.

**Comment by spoore1** [comment]
Yes, this finished a little while ago.  And calculating the amount of data, it took about the correct amount of time.  Since I had it limited to 10 bytes/s, it took 3hrs to run.

So, yes, this is already fixed in v5.

Thanks for the find.
