### ISSUE TITLE
ssh session hungs after disconnecting from a tlog recording

### ISSUE THREAD

**Issue by teroz** [Scribery/tlog#256]
Hey there
I have an Ubuntu 18.04.2 host that is part IPA domain and has session recording setup for all users. When I ssh in with an IPA user recording starts correctly. When I terminate the ssh session with CTRL-C the terminal hangs and ssh has to be killed.
Would you know why this is happening?

**Comment by spbnick** [comment]
Hi @teroz, are you running an interactive ssh session? If it's an interactive session, then Ctrl-C will go to the process on the remote machine and you'll need to find out why it doesn't terminate. If it's a non-interactive ssh session, then try running ssh with the `-v` option and see if there's any clue there.

**Comment by teroz** [comment]
Hey @spbnick session was an interactive session. Seems the issue was a gnome Shell desktop shell windowing problem as I was able to connect and disconnect from other terminal clients with no problem and syslog has it complaining about some mismatched timestamp.

**Comment by spbnick** [comment]
Huh, interesting, but I wouldn't like to dig into that kind of problem :) Does this reproduce with recording disabled?

**Comment by teroz** [comment]
Not happening any more after I restarted my gnome shell - definitely the worst kind of error to chase down :)
