### ISSUE TITLE
Feature request: Log commands separately

### ISSUE THREAD

**Issue by MrRagnar** [Scribery/tlog#260]
I don't know if this is a usable feature for many users but I would really love to have executed commands logged in a separate field.
This would make tlog include basically the bash history.

That will make it easier to set up alerts for specific commands run.
Right now it's hard since the `out_txt` field contains escape character and other control characters.

I understand that this will probably miss commands run in interactive sessions such as DB shells and the python interpreter but it will help greatly by eliminating the need for a separate solution for shell history ingestion.

I'm unfortunately not a good programmer so I can't help with a PR.

**Comment by spbnick** [comment]
@MrRagnar, this would be outside tlog's position in the system. This is a job for auditd. If you want to get auditd's logs to Elasticsearch, take a look at [aushape](https://github.com/Scribery/aushape/).

**Comment by MrRagnar** [comment]
All right!
That make's sense.
Thank you!
