### ISSUE TITLE
tlog commands: return "No such file or Directory Failed setting locale from environment variables" on Centos 7

### ISSUE THREAD

**Issue by rgiordani71** [Scribery/tlog#265]
I've just clone the git repo and built as described in the readme on Centos 7.
After installation without any errors I've tried to run the commands tlog-rec, tlog-rec-session and tlog-play, but I've got always the same messages even I have the commands in /usr/bin/ folder
>tlog-rec-session
No such file or directory
Failed setting locale from environment variables

What I've forgotten to configure after the installation?
Thanks

**Comment by justin-stephenson** [comment]
Tlog is attempting to read and set the environment locale settings
calling the glibc function setlocale() but not finding a valid locale.
This error occurs after checking the LC_ALL and LANG environment
variables, is it possible there are not set correctly due to custom
configuration in ~/.profile or /etc/profile? Another user who had the
same errors had a SendEnv line in /etc/ssh/ssh_config with bad 
environment variables defined, removing that line fixed this issue.

**Comment by rgiordani71** [comment]
Hi Justin,

I've fixed the LC_ALL and LC_CTYPE on /etc/environment

and now running the tlog-rec-session these are the messages

>tlog-rec-session
No such file or directory
Failed creating lock file /usr/var/run/tlog/session.22.lock
Assuming session was unlocked

ATTENTION! Your session is being recorded!


I've also added in system-auth the row

session required pam_env.so readenv=1 envfile=/etc/locale.conf


What else should I configure?

Thanks

**Comment by justin-stephenson** [comment]
Hello @rgiordani71 

In the following link:

https://github.com/Scribery/tlog#installing

It mentions the following:

You will also need to create the session lock directory /var/run/tlog and make it writable (only) for the user(s) tlog-rec-session runs as. On systems where (/var)/run is a tmpfs you will also need to make sure the session lock directory is recreated on the next boot. In that case, on systems with systemd you'll need to create a tmpfiles.d configuration file, and on init.d systems - a startup script, creating the directory for you.

tlog-rec-session should have the following permissions:
~~~
$ ll /usr/bin/tlog-rec-session 
-rwsr-sr-x. 1 tlog tlog 19352 Jun 12 10:46 /usr/bin/tlog-rec-session
~~~

**Comment by justin-stephenson** [comment]
Closing as this appears to be resolved, please re-open if needed.
