### ISSUE TITLE
Tlog doesn't like WINSCP

### ISSUE THREAD

**Issue by Zurg-kun** [Scribery/tlog#267]
Hello, 

I Have installed Tlog for two months, and to now there wasn't any problem, but when it comes to copy any files by WinSCP, Tlog goes crazy. When copying for example file of size 50MB, Tlog saves information about coping in binary at /var/logs/messagges and the messagges file increases by over 250MB. For now we get around the problem and we limited rate and burst in config but it isn't resolve problem. There should be some exclude about logging.

**Comment by spbnick** [comment]
AFAIK, it's difficult, if not impossible, to detect a difference between scp and normal sessions. Have you tried switching WinSCP to using SFTP protocol?

**Comment by Zurg-kun** [comment]
Unfortunately SFTP the same problem :c

**Comment by spbnick** [comment]
If it's really actually using SFTP, then I might have been confused about the way it's implemented. The most realistic and reliable workaround could be to use a separate non-recorded account for scp/sftp.

**Comment by justin-stephenson** [comment]
@Zurg-kun could you provide the steps to reproduce the problem? Does it occur when copying files(using WinSCP) when logging in as a tlog-enabled user?

**Comment by Zurg-kun** [comment]
I Have Tlog version 6 installed. In configuration file logging input is set to "true". When i copy files to server using WinSCP or FileZilla (using SFTP Protocol) files are copied successfully but increase logging file (/var/log/messages) is very huge. For example size of file /var/log/messages just 3MB screen nbr. 1. After copy file to server about size 90MB, the size of file messages increase to 634MB!  In file, there are many posts of Tlog (screen nbr.3) and because of the amount of posts like this the size incrase. 

![nbr1](https://user-images.githubusercontent.com/57432818/68369566-ec280c80-013a-11ea-8973-a6a8d57f5639.png)
![nbr2](https://user-images.githubusercontent.com/57432818/68369576-f0542a00-013a-11ea-9ba0-f285f76dfdef.png)
![nbr3](https://user-images.githubusercontent.com/57432818/68369581-f4804780-013a-11ea-8f68-ef00a6f2eb8a.png)

**Comment by Zurg-kun** [comment]
I forgot to write about non logging Tlog user, when it comes to copy files by user without Tlog logging, Tlog doesn't logging anythink to /var/log/messages. Is this the only solution to the problem?

**Comment by spbnick** [comment]
@Zurg-kun, it might be the only solution, at least short term. You can also try to disable sftp and scp for the logged user to reduce log size.

**Comment by Zurg-kun** [comment]
What is the status of problem? Have anyone tryed to reproduce the problem? If yes is it ended succesfull?

**Comment by justin-stephenson** [comment]
Hi @Zurg-kun as tlog is transferring raw I/O it is expected that the scp sessions will generate a large amount of tlog recorded messages. logging limit options or using a different user for SCP activity are the current workarounds for this.
