### ISSUE TITLE
Release Installation

### ISSUE THREAD

**Issue by ginsburgnm** [Scribery/tlog#268]
> You can use one of the release binary RPM packages and install them with your favorite tool.

There is either a bug in your release process or this documentation is no longer accurate; there are not release binary RPM packages after tlog release 5.

**Comment by justin-stephenson** [comment]
@ginsburgnm My mistake, I added the Fedora release rpms now to the release v7. Let me know if that is what you are looking for, or not.

https://github.com/Scribery/tlog/releases/tag/v7

**Comment by ginsburgnm** [comment]
LGTM
