### ISSUE TITLE
tlog prevents logins if it can't determine the local hostname

### ISSUE THREAD

**Issue by trevor-vaughan** [Scribery/tlog#269]
Due to a system configuration error, it was discovered that tlog-rec-session will fail to start if the system hostname cannot be determined.

The easiest way to reproduce this is to edit `/etc/nsswitch.conf` and set the `hosts` entry to `files`. Then, remove any entries related to the local host (besides 127.0.0.1 entries) from `/etc/hosts`.

At this point, setting a user's shell to `tlog-rec-session` should result in the user being unable to access the system.

Given that this may be set to the `root` user's account, this should not be a failing scenario for system access.

Now, adding `myhostname` to the end of the `hosts` line **does** remedy the issue, but I don't think that this should be a failure case for tlog at any rate. Anything preventing users from actually accessing the system due to external system configuration issues is quite bad.

**Comment by justin-stephenson** [comment]
Thanks @trevor-vaughan I think we should fix this. I will need to test further but I don't see much loss in functionality if we fall back to something like `unknownhost` if the hostname cannot be determined.

**Comment by spbnick** [comment]
I would recommend using empty string, or, maybe even better, omitting the `hostname` property altogether if tlog failed to determine the hostname.

**Comment by justin-stephenson** [comment]
This is fixed in https://github.com/Scribery/tlog/commit/bf97227fd08d4ead58748492f2ac0b2c25b2771c
