### ISSUE TITLE
tlog-play : Message ID is out of order issue

### ISSUE THREAD

**Issue by msg2ashish** [Scribery/tlog#275]
Message ID is out of order=
Failed reading the source at entry 13

"session":218,"id":1,"
"session":218,"id":2,"
"session":218,"id":3,"
"session":218,"id":4,"
"session":218,"id":5,"
"session":218,"id":6,"
"session":218,"id":7,"
"session":218,"id":8,"
"session":218,"id":9,"
"session":218,"id":10,
"session":218,"id":11,
"session":218,"id":12,
"session":218,"id":13,   
"session":218,"id":1," **ID no reset breaks tlog-pay with Message ID is out of order=**
"session":218,"id":2,"
"session":218,"id":3,"
"session":218,"id":4,"
"session":218,"id":5,"
"session":218,"id":6,"
"session":218,"id":7,"
"session":218,"id":8,"
"session":218,"id":1,"
"session":218,"id":2,"
"session":218,"id":3,"
"session":218,"id":4,"
"session":218,"id":5,"
"session":218,"id":6,"
"session":218,"id":7,"
"session":218,"id":8,"
"session":218,"id":9,"
"session":218,"id":10,
"session":218,"id":11,
"session":218,"id":12,
"session":218,"id":1,"
"session":218,"id":2,"
"session":218,"id":3,"
"session":218,"id":4,"

**Comment by justin-stephenson** [comment]
Hello @msg2ashish could you help provide some idea of how this problem occurs in your environment, or if you can provide clear reproducer steps it would be much appreciated(and tlog version, also).

**Comment by justin-stephenson** [comment]
Closing as this appears to be stale/unanswered, please re-open if needed.
