### ISSUE TITLE
/usr/bin/tlog-rec-session on Ubuntu stopped working

### ISSUE THREAD

**Issue by milos-cuculovic** [Scribery/tlog#292]
Today, the /usr/bin/tlog-rec-session is no longer er working on Ubuntu 18.04 LTS. I am using it together with FreeIPA and the ssh login is stuck for some time and then prints:

    ATTENTION! Your session is being recorded!

    Cannot allocate memory
    Failed forking a child connected via a PTY
    Failed setting up the I/O tap
    Connection to 212.243.204.48 closed.

    [Process completed]

**Comment by spbnick** [comment]
@justin-stephenson, looks like forkpty is returning ENOMEM.

**Comment by milos-cuculovic** [comment]
On another server, tlog is returning

    lh_table_new: calloc failed
    Connection to 212.243.204.22 closed.

**Comment by spbnick** [comment]
@milos-cuculovic, could it be you're running out of some memory allocation limit?

**Comment by milos-cuculovic** [comment]
@spbnick , no, we have this issues on many servers running Ubuntu 18.04.

**Comment by spbnick** [comment]
@milos-cuculovic, anything in dmesg, audit.log?

**Comment by milos-cuculovic** [comment]
Here is what I have in syslog

`May 15 09:19:20 storage3-old kernel: [8812442.362492] audit: type=1400 audit(1589534360.273:49236): apparmor="ALLOWED" operation="open" profile="/usr/sbin/sssd" name="/etc/selinux/semanage.conf" pid=1287872 comm="selinux_child" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
May 15 09:19:20 storage3-old systemd[1]: Created slice User Slice of cuculovic.
May 15 09:19:20 storage3-old systemd[1]: Starting User Manager for UID 129800003...
May 15 09:19:20 storage3-old systemd[1]: Started Session 3080 of user cuculovic.
May 15 09:19:20 storage3-old kernel: [8812442.384893] audit: type=1400 audit(1589534360.297:49237): apparmor="ALLOWED" operation="open" profile="/usr/sbin/sssd" name="/etc/selinux/semanage.conf" pid=1287874 comm="selinux_child" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
May 15 09:19:20 storage3-old systemd[1287873]: Listening on GnuPG cryptographic agent and passphrase cache.
May 15 09:19:20 storage3-old systemd[1287873]: Listening on GnuPG network certificate management daemon.
May 15 09:19:20 storage3-old systemd[1287873]: Listening on REST API socket for snapd user session agent.
May 15 09:19:20 storage3-old systemd[1287873]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
May 15 09:19:20 storage3-old systemd[1287873]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
May 15 09:19:20 storage3-old systemd[1287873]: Reached target Timers.
May 15 09:19:20 storage3-old systemd[1287873]: Reached target Paths.
May 15 09:19:20 storage3-old systemd[1287873]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
May 15 09:19:20 storage3-old systemd[1287873]: Reached target Sockets.
May 15 09:19:20 storage3-old systemd[1287873]: Reached target Basic System.
May 15 09:19:20 storage3-old systemd[1287873]: Reached target Default.
May 15 09:19:20 storage3-old systemd[1287873]: Startup finished in 24ms.
May 15 09:19:20 storage3-old systemd[1]: Started User Manager for UID 129800003.
May 15 09:19:21 storage3-old systemd[1]: Stopping User Manager for UID 129800003...
May 15 09:19:21 storage3-old systemd[1287873]: Stopped target Default.
May 15 09:19:21 storage3-old systemd[1287873]: Stopped target Basic System.
May 15 09:19:21 storage3-old systemd[1287873]: Stopped target Sockets.
May 15 09:19:21 storage3-old systemd[1287873]: Closed REST API socket for snapd user session agent.
May 15 09:19:21 storage3-old systemd[1287873]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
May 15 09:19:21 storage3-old systemd[1287873]: Closed GnuPG cryptographic agent (ssh-agent emulation).
May 15 09:19:21 storage3-old systemd[1287873]: Closed GnuPG network certificate management daemon.
May 15 09:19:21 storage3-old systemd[1287873]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
May 15 09:19:21 storage3-old systemd[1287873]: Stopped target Paths.
May 15 09:19:21 storage3-old systemd[1287873]: Stopped target Timers.
May 15 09:19:21 storage3-old systemd[1287873]: Closed GnuPG cryptographic agent and passphrase cache.
May 15 09:19:21 storage3-old systemd[1287873]: Reached target Shutdown.
May 15 09:19:21 storage3-old systemd[1287873]: Starting Exit the Session...
May 15 09:19:21 storage3-old systemd[1287873]: Received SIGRTMIN+24 from PID 1287967 (kill).
May 15 09:19:21 storage3-old systemd[1]: Stopped User Manager for UID 129800003.
May 15 09:19:21 storage3-old systemd[1]: Removed slice User Slice of cuculovic.
`

**Comment by milos-cuculovic** [comment]
In dmesg:

`[8812612.105309] audit: type=1400 audit(1589534530.017:49239): apparmor="ALLOWED" operation="open" profile="/usr/sbin/sssd" name="/etc/selinux/semanage.conf" pid=1288004 comm="selinux_child" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
`

**Comment by milos-cuculovic** [comment]
In auth.log::

`May 15 09:23:18 storage3-old sshd[1288122]: Accepted publickey for cuculovic from 185.165.33.148 port 7734 ssh2: RSA SHA256:pQPmMbrHC2zmHYWMhkDuVhjNIfjUSNfvIc9d1iLkaMg
May 15 09:23:18 storage3-old sshd[1288122]: pam_unix(sshd:session): session opened for user cuculovic by (uid=0)
May 15 09:23:18 storage3-old systemd-logind[1909]: New session 3084 of user cuculovic.
May 15 09:23:18 storage3-old systemd: pam_unix(systemd-user:session): session opened for user cuculovic by (uid=0)
May 15 09:23:19 storage3-old sshd[1288220]: Received disconnect from 185.165.33.148 port 7734:11: disconnected by user
May 15 09:23:19 storage3-old sshd[1288220]: Disconnected from user cuculovic 185.165.33.148 port 7734
May 15 09:23:19 storage3-old sshd[1288122]: pam_unix(sshd:session): session closed for user cuculovic
May 15 09:23:19 storage3-old systemd-logind[1909]: Removed session 3084.
`

**Comment by spbnick** [comment]
Can't see anything wrong in the logs.

**Comment by milos-cuculovic** [comment]
Right, looks clean. However, somehow tlog is not working. Is there a way to run it in verbose by calling it manually /usr/bin/tlog-rec-session ?

**Comment by milos-cuculovic** [comment]
https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg5777565.html

**Comment by spbnick** [comment]
@milos-cuculovic, nice catch! This would definitely do it.

**Comment by milos-cuculovic** [comment]
Looking forward for their fix I think I can close this ticket as it is not related to Tlog?

**Comment by spbnick** [comment]
Yes, closing. Thank you for the report!
