### ISSUE TITLE
Custom Shell functionality broken

### ISSUE THREAD

**Issue by mp-bgp** [Scribery/tlog#294]
## Expected Behavior
According to [https://github.com/Scribery/tlog#configuring-shell-per-user-using-symlinks](https://github.com/Scribery/tlog#configuring-shell-per-user-using-symlinks), when calling tlog-rec-session through a symlink containing a path to a shell (e.g. /usr/bin/tlog-rec-session-bin-zsh), this shell should be launched instead of bash.
## Current Behavior
No matter how the symlink is called, it launches bash.

## Steps to Reproduce
1. Create symlink to tlog-rec-session:
```bash
ln -s /usr/bin/tlog-rec-session /usr/bin/tlog-rec-session-bin-zsh
```
2. Call symlink
```bash
[root@862f4a0254f3]/# /usr/bin/tlog-rec-session-bin-zsh
Locale charset is ANSI_X3.4-1968 (ASCII)
Assuming locale environment is lost and charset is UTF-8

ATTENTION! Your session is being recorded!

[root@862f4a0254f3 /]# echo $0
/bin/bash
[root@862f4a0254f3 /]# ls /bin/zsh
/bin/zsh
[root@862f4a0254f3 /]# ls -lah /bin/zsh
-rwxr-xr-x 1 root root 724K Apr  7 14:37 /bin/zsh
[root@862f4a0254f3 /]# grep shell /etc/tlog/tlog-rec-session.conf
    // The path to the shell executable which should be spawned.
    // "shell" : "/bin/bash",
    // recording and the user shell. Can be used to warn
```

## Context (Environment)
It recently stopped working on our custom build on centos:7. Therefore I tested it on fedora32 with the provided rpm as well.
```bash
[root@be9288840fd8 /]# /usr/bin/tlog-rec-session-bin-zsh

ATTENTION! Your session is being recorded!

[root@be9288840fd8 /]# echo $0
/bin/bash
[root@be9288840fd8 /]# /bin/zsh
[root@be9288840fd8]/# echo $0
/bin/zsh
[root@be9288840fd8]/#
```

**Comment by justin-stephenson** [comment]
@mp-bgp I guess you forgot to include the `-shell-` in the symlink name:
~~~
# ln -s /usr/bin/tlog-rec-session /usr/bin/tlog-rec-session-shell-bin-zsh
~~~

**Comment by mp-bgp** [comment]
PEBKAC - nevermind. Thanks for your help.
