### ISSUE TITLE
Check timing delay range is within TLOG_DELAY_MAX in source

### ISSUE THREAD

**Issue by spbnick** [Scribery/tlog#30]

**Comment by spbnick** [comment]
This basically means adding assertions to various tlog sources, including the abstract interface, that the successively returned packets are not more than TLOG_DELAY_MAX apart. Any associated data or initialization code should be compiled in debug build only, i.e. be under `#ifndef NDEBUG` conditions.

**Comment by danghai** [comment]
When I look the man page for `assert` . 
       If  the  macro  NDEBUG  is  defined  at  the moment <assert.h> was last
       included, the macro assert() generates no code, and hence does  nothing
       at  all.   It  is not recommended to define NDEBUG if using assert() to
       detect error conditions since the software may behave non-deterministi‐
       cally.

And I am not sure, why do you need the NDEBUG. Can you explain more? Do you use it for DEBUG option? I mean if it violates the TLOG_DELAY_MAX, it will give the message about it and abort? 
I have another question about `delay.h`. I see it is inside lib but you never include it. Do you use the macro NDEBUG in it?

**Comment by spbnick** [comment]
I'm using `assert` with NDEBUG as a compromise. With assert I only check conditions which can arise from internal, coding errors (at least that's the intention). All other, outside errors, e.g. from OS conditions, user input, etc. are checked with regular conditions and error handling.

I do testing without NDEBUG defined (with --enable-debug option specified), i.e. with `assert` invocations intact, but I define NDEBUG in production builds (without --enable-debug) to improve performance, as all the checks through the code are slowing it down. If a distro packager is OK with reduced performance, they might choose to not define NDEBUG for their build. It's a debatable practice, but one that I follow for now.

If you do not have NDEBUG defined, e.g. if you configured the build with the --enable-debug option, and your `assert` invocations are in effect, then when one fails, a message will be printed and the process will be killed by SIGABRT, producing a coredump, if that's enabled.

If you'd like, write a small program using `assert` and try building and running it with and without NDEBUG defined and assertion failing.

delay.h is in include/tlog, and it's included into seven files. You can find them as such: `grep -r --include '*.[hc]' delay.h *`.

**Comment by danghai** [comment]
I understand what you mean about NDEBUG or DEBUG through building and running a simple example.
```
#include <stdio.h>
//# define NDEBUG
#include <assert.h>

int main(){
    assert(1==2);
    return 0;
}
```

I am not sure about using TLOG_DELAY_MAX. you mean you just want to check assert for only TLOG_DELAY_MAX and NOT DEBUG for the rest of assert() in your code in preprocessor. And I need to modify all these change `include <assert.h>` for each `*.c` and `.*h` file? 
 
```
#ifdef DEBUG
/*  assert(TLOG_DELAY_MAX) for Debug */
#else
#define NDEBUG
#include <assert.h>
#endif
```

**Comment by danghai** [comment]
Hi Nick, I am not sure the variable storing returned packet time. I think the variable : pkt_last_ts. Please review my commit, it satisfies your requirement in issue? 
 https://github.com/danghai/tlog/commit/79435b3de16adadd2544d08f397d6782cfa41308

**Comment by spbnick** [comment]
We're getting there, but it's not exactly what needs to be done yet. First, you don't need to put `#ifndef NDEBUG` around `assert` invocations, because that is taken care of in `/usr/include/assert.h`. Take a closer look there. If `NDEBUG` is defined, then `assert` is defined as a no-op, i.e. it does nothing and produces no code. Only if `NDEBUG` is not defined, then `assert` is defined to code which checks its condition and aborts if it fails.

Next, you need to put these `assert` checks not into tlog-play's `run()`, but at returns from all `tlog_source_*` functions, which output a packet. E.g. the `tlog_source_read` function. The asserts should verify that timestamp in each returned packet is at most `TLOG_DELAY_MAX` greater than the timestamp in the packet that function returned last, or from zero timestamp, if it's the first packet the function returns.

This makes sure that we can actually encode packet streams coming from sources into the documented tlog message JSON format correctly.

**Comment by danghai** [comment]
for tlog_source_*, I see only 1 function relating to pkt (`tlog_source_read`). Or you mean it includes `tlog_json_source_read`. 
I send the update commit in `tlog-play`. You mean I need to make sure `pkt` must have `timestamp` is in range `TLOG_DELAY_MAX` by adding all assert after function `tlog_source_*` for the rest of the code? 
https://github.com/danghai/tlog/commit/4baf9c35ddbd340714279ceb25fdd2e9efbd3521

Another question, I do not realize that in pkt it has `timestamp` with type: `timespec` until you mention it because when I read `pkt.h`. I do not see you include `time.h`.

**Comment by spbnick** [comment]
Making `tlog_source_read` check what it returns would be a good start. However, we might add checks to specific source types as well after that.

What your change needs to do is add a call to `assert` *inside* `tlog_source_read`, which would check that the packet it returns *now* has timestamp which is not more than TLOG_DELAY_MAX greater than the packet it returned *last time*. For that purpose you would need to add a field to `struct tlog_source` instance storing the timestamp of the packet returned last (or zero timestamp if there were no packets returned yet), checking each packet against it, and then updating it. You don't need to modify `tlog-play.c` at all.

**Comment by danghai** [comment]
I add a field to `struct tlog_source`. But I am not sure about how I can store zero timestamp if there were no packets returned. I check timestamt is not more than TLOG_DELAY_MAX and greater than the packet it returned last time. If it passes, update timestamp in source. Could you check my commit to make sure that I follow the right direction. 
https://github.com/danghai/tlog/commit/43a1f88ed8458006e065984d18b09298281a787e

**Comment by spbnick** [comment]
This is getting closer. You don't need to take care about initializing the timestamp to zero, as `calloc` in `tlog_source_create` takes care of that (read `man calloc`). You found the right place where to put this, but you need to work on comparison. As of now you're only checking that the absolute returned timestamp is less than TLOG_DELAY_MAX, and that the new timestamp is greater than the previous one. You need to check if the difference between the new and the old timestamp is <= TLOG_DELAY_MAX.

**Comment by danghai** [comment]
Oh `calloc`  sets allocated memory to zero where `alloc` does not set the memory to zero.  I check the difference between the new and the old timestamp is <= TLOG_DELAY_MAX and it must be greater than 0. However, I am not sure about why you need to check the difference timespec. You can review my commit about these change: 
https://github.com/danghai/tlog/commit/5487f196614aca4191d5752a9478a2484114bc6d

**Comment by spbnick** [comment]
We need this check for portability to 32-bit architectures, where .tv_sec is a 32-bit signed integer, whereas 64-bit architectures have it 64-bit. If a log is written on 64-bit archs, we need to be able to read it on 32-bit arch, and therefore delays between packets cannot be more than 32-bit architecture can represent. Overflowing the signed 32-bit integer in normal time wouldn't happen, as the project would be dead by then (in 70 years), but we still need to protect from overflows, at least in testing. It would be good to also catch it in production build somehow.

**Comment by spbnick** [comment]
Yeah, we only need the two bottom asserts.
