### ISSUE TITLE
unable to compile code for ubuntu 18.04 or even 20.04

### ISSUE THREAD

**Issue by teroz** [Scribery/tlog#302]
Hi there
I tried to compile the relesed tar file. I installed the prerequistes inclouding libjson-c-dev but I ran into this issue

```bash
checking for PTHREAD_PRIO_INHERIT... yes
./configure: line 14039: syntax error near unexpected token `JSON,'
./configure: line 14039: `PKG_CHECK_MODULES(JSON, json-c)'
```
What do you think the issue is?

**Comment by justin-stephenson** [comment]
Hello @teroz ,

I tried but was unable to reproduce this problem on my local **ubuntu 20.04** VM.

I extracted the archive https://github.com/Scribery/tlog/releases/download/v8-2/tlog-8.tar.gz then installed build dependencies per the tlog README:

`libjson-c-dev libsystemd-journal-dev libsystemd-dev libcurl4-openssl-dev libutempter-dev pkg-config`

and

`autoconf automake libtool make`

autoreconf and configure was successful. Could you provide your `config.log` ?

**Comment by teroz** [comment]
Thank you @justin-stephenson. I was doing my install on a remote VPS. I just spun up another VM and it worked great. Thank you so much
