### ISSUE TITLE
tlog fails when using ssh -J or Jump configuration in .ssh/config 

### ISSUE THREAD

**Issue by vindian** [Scribery/tlog#303]
tlog works fine using standard ssh login into the jump server or while running an Ansible command.
However, when using -J option with ssh, it fails to record user commands being sent to backend via the bastion host.

**Comment by justin-stephenson** [comment]
Thanks for reporting this issue, I'll need to do some investigation to determine if, or how this can be fixed on our side.

Does the user initiating the SSH connection also have their shell set as tlog-rec-session on the jump host system?

**Comment by vindian** [comment]
User is from IDM and has the following in /etc/sssd/conf.d/sssd-session-recording.conf

[session_recording]
scope=some
users=testuser2
groups=

**Comment by spbnick** [comment]
I would suspect that the only way to enforce jump-host recording would be to disable sshd TCP forwarding on the jump host, effectively disabling support for -J option, and forcing a full login on the jump-host before logging into the target. The sshd_config option would probably be `AllowTcpForwarding local`.

**Comment by vindian** [comment]
That would not be suitable if end users are using it purely as jump server. Especially when they want to use clients like Putty and SecureCRT as a user friendly way of having target server entries stored in the client. 

-J options supports that, if tlog can work with it, it will be feasible for Admins to enable it without causing inconvenience to users or needing to make changes to the backend servers

**Comment by justin-stephenson** [comment]
Unfortunately this is not possible to enable recording when a shell is never spawned on the intermediate host, which is the case of TCP forwarding using SSH's `ProxyJump` option. Closing.
