### ISSUE TITLE
Fedora RPM package adoption

### ISSUE THREAD

**Issue by kees-closed** [Scribery/tlog#332]
As per Fedora package guidelines, I'm just letting you know I'm in the process to adopt the RPM package. The previous owner is too busy to maintain it.

Background about the adoption: https://bugzilla.redhat.com/show_bug.cgi?id=1977335
New review process: https://bugzilla.redhat.com/show_bug.cgi?id=1997521

Which also leaves me with some questions for the upstream devs.
* Is a [development package](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_devel_packages) needed? At the moment this is not done. In the fedora-devel IRC room people think this is also not needed. But best to confirm with you.
* Could you please check in the [spec file](https://fedorapeople.org/cgit/keesdejong/public_git/rpmbuild.git/tree/SPECS/tlog.spec#n57) if the SUID/SGID is set correctly for tlog-rec-session? I believe it's set as documented in your [README.md](https://github.com/Scribery/tlog#installing), but this is something to double check.
* Some Fedora devs were wondering if the SUID/SGID is really needed.

**Comment by justin-stephenson** [comment]
Hi, I still am responsible for maintaining tlog, and will continue to do so. In the BugZilla I only meant that I do not have plans to prepare packages for EPEL specifically. Apologies for the confusion.
