### ISSUE TITLE
Playing back from Elasticsearch

### ISSUE THREAD

**Issue by asow25** [Scribery/tlog#350]
Hi everyone, I'm Abdoul, IT trainee. I'd like to realize User Session Recording Project. I installed Rsyslog, Elasticsearch and Kibana, no problem at all. Further, I get the logs on my GUI. Long story short, I cannot to play the sessions from elasticsearch. I don't find any errors; I'm confused. Please, some help would be welcome. 
Is it correct that there are many log lines for a single session? Here's my stdout :

[root@srv ~]# curl -s 192.168.100.166:9200/tlog-rsyslog/_search | jq . | grep rec
          "rec": "ada0acb659c24c318f17edc83334110c-ea9-580b72",
          "rec": "ada0acb659c24c318f17edc83334110c-ea9-580b72",
          "rec": "ada0acb659c24c318f17edc83334110c-ea9-580b72",
          "rec": "ada0acb659c24c318f17edc83334110c-ea9-580b72",
          "rec": "ada0acb659c24c318f17edc83334110c-ea9-580b72",
          "rec": "ada0acb659c24c318f17edc83334110c-ea9-580b72",
          "rec": "ada0acb659c24c318f17edc83334110c-ea9-580b72",
          "rec": "ada0acb659c24c318f17edc83334110c-ea9-580b72",
          "rec": "ada0acb659c24c318f17edc83334110c-ea9-580b72",
          "rec": "ada0acb659c24c318f17edc83334110c-ea9-580b72",

[root@srv ~]# journalctl -xel _EXE=/usr/bin/tlog-rec-session 
déc. 21 11:30:20 srvprod-test.mycompany.ci -tlog-rec-session[3753]: {"ver":"2.3","host":"srvprod-test.mycompany.ci","rec":"ada0acb659c24c318f17edc83334110c-ea9-580b72","user":""
déc. 21 11:30:20 srvprod-test.mycompany.ci -tlog-rec-session[3753]: {"ver":"2.3","host":"srvprod-test.mycompany.ci","rec":"ada0acb659c24c318f17edc83334110c-ea9-580b72","user":""
déc. 21 11:30:20 srvprod-test.mycompany.ci -tlog-rec-session[3753]: {"ver":"2.3","host":"srvprod-test.mycompany.ci","rec":"ada0acb659c24c318f17edc83334110c-ea9-580b72","user":""
déc. 21 11:30:20 srvprod-test.mycompany.ci -tlog-rec-session[3753]: {"ver":"2.3","host":"srvprod-test.mycompany.ci","rec":"ada0acb659c24c318f17edc83334110c-ea9-580b72","user":""
déc. 21 11:30:20 srvprod-test.mycompany.ci -tlog-rec-session[3753]: {"ver":"2.3","host":"srvprod-test.mycompany.ci","rec":"ada0acb659c24c318f17edc83334110c-ea9-580b72","user":""
déc. 21 11:30:20 srvprod-test.mycompany.ci -tlog-rec-session[3753]: {"ver":"2.3","host":"srvprod-test.mycompany.ci","rec":"ada0acb659c24c318f17edc83334110c-ea9-580b72","user":""
déc. 21 11:30:20 srvprod-test.mycompany.ci -tlog-rec-session[3753]: {"ver":"2.3","host":"srvprod-test.mycompany.ci","rec":"ada0acb659c24c318f17edc83334110c-ea9-580b72","user":""
déc. 21 11:30:20 srvprod-test.mycompany.ci -tlog-rec-session[3753]: {"ver":"2.3","host":"srvprod-test.mycompany.ci","rec":"ada0acb659c24c318f17edc83334110c-ea9-580b72","user":""
déc. 21 11:30:20 srvprod-test.mycompany.ci -tlog-rec-session[3753]: {"ver":"2.3","host":"srvprod-test.mycompany.ci","rec":"ada0acb659c24c318f17edc83334110c-ea9-580b72","user":""
déc. 21 11:30:20 srvprod-test.mycompany.ci -tlog-rec-session[3753]: {"ver":"2.3","host":"srvprod-test.mycompany.ci","rec":"ada0acb659c24c318f17edc83334110c-ea9-580b72","user":""

[root@srvp ~]# cat /etc/tlog/tlog-play.conf 
{
    "reader": "es",
    "es" : {
    "baseurl": "http://192.168.100.166:9200/tlog-rsyslog/tlog/_search"
    },
}

[root@srvprod-test ~]# tlog-play -r es --es-baseurl=http://192.168.100.166:9200/tlog/tlog/_search --es-query=session:17 --es-verbose
*   Trying 192.168.100.166...
                             * TCP_NODELAY set
                                              * Connected to 192.168.100.166 (192.168.100.166) port 9200 (#0)
                                                                                                             > GET /tlog/tlog/_search?q=session%3A17&sort=id%3Aasc&size=10&from=0 HTTP/1.1
Host: 192.168.100.166:9200
Accept: */*

* The requested URL returned error: 404 Not Found
                                                 * Closing connection 0

HTTP response code said error
Failed reading the source at message #0
[root@srvprod-test ~]#

**Comment by asow25** [comment]
Thanks a lot, I found it, it works.

**Comment by iskenyildiz** [comment]
what was the solution?

**Comment by sowabdoul** [comment]
It's been a while, but I think the issue was with the syntax. Try the following, replacing the placeholders as needed:

```bash
curl -s https://<ELASTIC_URL>/<INDEX_NAME>/_search | jq . | grep rec

curl -XGET 'https://<ELASTIC_URL>/<INDEX_NAME>/tlog/_search?pretty'

tlog-play --lax -r es \
  --es-baseurl=https://<ELASTIC_URL>/<INDEX_NAME>/tlog/_search \
  --es-query="session:6 AND timestamp:>=now-7d"

tlog-play -r journal -M TLOG_REC=<SESSION_ID>
```

Are you comfortable with Ansible?
Back then, I wrote a playbook to install and configure the whole stack at scale.
