### ISSUE TITLE
HOW to get TLOG working in Ubuntu/Debian!?????

### ISSUE THREAD

**Issue by msilveirabr** [Scribery/tlog#351]
I'm having a hard time getting it to work in Ubuntu 22.04LTS...

Any guide on how to get it working? I have it working fine under RHEL and clones.

If you have it working, please post steps here, no matter what Ubuntu version !

**Comment by justin-stephenson** [comment]
Hi, are you following the steps in the [README](https://github.com/Scribery/tlog#installing)  ?

What errors are you seeing?

It has been a bit since I tried using tlog on Ubuntu but it was working fine for me here https://github.com/Scribery/tlog/issues/302

**Comment by msilveirabr** [comment]
Hi @justin-stephenson .
After some more testing, I know that the official package is available only in jammy ( 22.04 ) + release.
I get it setup just about the same way I do with rhel systems.
manual testing works fine, sssd auto_rec doesn't.
I'm asking for directions to get tlog auto record sessions using sssd nss/pam , just like in rhel systems.

Thanks.

**Comment by justin-stephenson** [comment]
You can use the [SSSD configuration method ](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/recording_sessions/deploying-session-recording-getting-started-with-session-recording#configuring-recorded-users-or-user-groups-with-sssd-from-cli-deploying-session-recording)(preferred). If you use SSSD for local users then you need to have 'sss' before 'files' in /etc/nsswitch.conf

Or [without SSSD.](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/recording_sessions/deploying-session-recording-getting-started-with-session-recording#configuration-of-recorded-users-or-user-groups-without-sssd-deploying-session-recording).

Hope this helps.

**Comment by msilveirabr** [comment]
Thanks @justin-stephenson I was trying to get simple local auth working before other methods.
I was just about to perform a diff between /etc folder before sssd and after ssd in fedora to check what changed, and sss as first entry in nsswitch.conf passwd and group sections did the trick.
The "without SSSD" part, I was suspicious that worked as described.

I'm not very used debian/ubuntu, trying to change this, creating my development/pkg build vm ubuntu versions  for 16.04+ .

Thanks again!

**Comment by msilveirabr** [comment]
Another necessary step to avoid lock file permissions:
chmod u+s,g+s /usr/bin/tlog-rec-session

If using the official ubuntu 22.04 package, when building cockpit-session-recording, edit src/recordings.jsx, find the line
```
const proc = cockpit.spawn(["getent", "passwd", "tlog"]);
```
replace tlog with _tlog 
```
const proc = cockpit.spawn(["getent", "passwd", "_tlog"]);
```

And replace 
```
        let authselect_cmd = ["authselect", "select", "sssd", "with-files-domain", "--force"];
```
with
```
        let authselect_cmd = ["/usr/bin/true"];

```

**Comment by justin-stephenson** [comment]
@msilveirabr If you would like to submit a Pull Request for the README about setting up tlog in ubuntu, that would be great.
