### ISSUE TITLE
Failed creating lock file

### ISSUE THREAD

**Issue by Kira19544** [Scribery/tlog#358]
Hello there, every time I log onto my server via SSH the message "Permission denied: Failed creating lock file /var/run/tlog/session.687.lock: Assuming session was unlocked" 

I try the best to fix this issue, already done what is described in issue #182 but I can't find any solution. 
Do you have any Ideas? 

System: Ubuntu Server 22.04. LTS, tlog verision: 12 installed over apt.

Sry for my bad english.

**Comment by justin-stephenson** [comment]
Hi, can you validate the following permissions/ownership are set:
~~~
[justin@fedora ~]$ ll /usr/bin/tlog-rec-session
-rwsr-sr-x. 1 tlog tlog 44672 Mar  2 12:08 /usr/bin/tlog-rec-session

[justin@fedora ~]$ ll -d /var/run/tlog/
drwxr-xr-x. 2 tlog tlog 40 Mar 28 10:13 /var/run/tlog/
~~~

**Comment by Kira19544** [comment]
Hi, now it works, I haven't changed the SUID/SGID of the binary. 

Thank you very much!
