### ISSUE TITLE
Allow for "echo only" recording capabilities

### ISSUE THREAD

**Issue by trevor-vaughan** [Scribery/tlog#77]
I understand why keystroke logging is the default but I **really** don't want user passwords, or other sensitive information, captured by `tlog`.

Instead, I would like to have the option to enable `echo only` logging which would only capture items that are echoed back to the screen.

I do understand that this will not be perfect but combining it with `pam_tty_audit` should be good enough and, of course, reviewing your logs for things that are happening when a user turns off echo.

Regardless, it is much more likely that a user will just copy in a script and execute it to avoid detection instead of going through the trouble of typing blind. And, of course, auditd can also be configured to capture the execution.

**Comment by spbnick** [comment]
Hi Trevor,

Thank you very much for your feedback, we need it.

First of all, let's deal with the simple matter of input capture by default. Regardless of everything else, would you like the default to be not recording user input? If so, and if most people want the same, we'll change it.

Regarding `echo only`, AFAIK, at the moment there is no interface for the userspace to detect that condition. Perhaps we can make one, and it would be accepted into the kernel, but I won't bet on it.

Combining with `pam_tty_audit` is actually an interesting idea. We're working on feeding audit logs to Elasticsearch anyway in [aushape](https://github.com/Scribery/aushape). Perhaps we can provide an option to extract input from pam_tty_audit log messages in the playback WebUI component we're designing. That wouldn't concern tlog, though, apart from disabling input recording.

Otherwise, yes, there is a myriad of ways for a user to escape recording, and in general the purpose of tlog is to rather capture the intention than the act. I.e. anything suspicious that precedes a transgression. For that purpose, in most cases output recording will be sufficient and input recording can be turned off, IMHO.

What do you think?

If you're coming to FOSDEM, I will be glad to meet and talk to you after [my talk](https://fosdem.org/2017/schedule/event/session_recording/) there.

**Comment by trevor-vaughan** [comment]
Hi Nikolai,

Unfortunately Brussels (while awesome) is a bit out of my budget this year :smile:. I'll try to catch the recording if they have one though.

To cross threads, I'm very much interested in ditching the (now unmaintained) `sudosh2` that we've been using and having a Red Hat sponsored project seems like a good way to go.

Back on topic, I would definitely like the default to be ignoring user input by default. `pam_tty_audit` managed to do this using ICANON checking (https://lists.fedorahosted.org/pipermail/linux-pam-commits/2013-June/000147.html).

In terms of stuffing things in ES, I'm a huge fan. Taking a quick look at `aushape`, you're going to need to denormalize your data if you want to be able to use it with Kibana and/or Grafana natively. Nested data structures just don't work well right now.

Looking forward to seeing where this goes.

**Comment by spbnick** [comment]
Pity you won't make it, I could have used your experience in this, if you'd share it. I'm pretty sure there will be recordings, though.

I can say that Red Hat is quite excited about this internally as well.

We discussed echo-only recording at Red Hat quite a while ago and my memories can be confused, but I do remember there were some difficulties with detecting no-echo mode from user-space, as opposed to kernel-space TTY audit. However, I will leave this issue open and will recheck that, when I come around to it.

Glad to see another ES supporter. Yes, I'm aware of Kibana difficulties with nested objects, however, I haven't used Kibana that much in practice. I haven't touched Graphana at all yet. Aushape has only a few record types stored as nested objects so far (PATH, OBJ_ID and AVC), although they might be very important to search for. The current plan is to let users choose whether to actually index them as nested objects or not. If they do, then they become unsearchable by Kibana (but still searchable directly in ES), if they don't, then they're flattened and are kind-of searchable.

Regarding denormalization, we don't have separate types/indexes for nested objects, only one of either, and there are only one-to-many relationships, and no many-to-one, so no need to duplicate data.

Come again and report more issues, and definitely patches, if you can!

**Comment by spbnick** [comment]
Another thing that can work as a compromise is the optional logging of source log messages. If enabled, then the source log messages can be used to look for the data in nested objects in a pinch, while preserving the structure otherwise.

**Comment by trevor-vaughan** [comment]
I'd be happy to share my experiences from using `sudosh2` in anger.

In terms of the denormalization, that is purely for allowing Kibana and Grafana to do their thing without having to write crazy back-ends.

As part of the [SIMP](https://simp.readthedocs.org) project, we've settled on Grafana by default since it is extremely safe in terms of query capabilities as well as providing LDAP and multi-tenant support out of the box. You definitely want Kibana as a "I don't know what I'm looking for" tool though.

If we have time, we'll see if we can help on tlog. Unfortunately, right now, we're swamped with massive code updates across 100k+ lines of code!

**Comment by spbnick** [comment]
"using sudosh2 in anger"? I feel there's quite a story behind this!

Can you describe briefly what a "crazy back-end" would look like?

What do you mean by "safe in terms of query capabilities"? That it doesn't let users overload ES with a query? That it can limit the data you can search for? Something else?

We all have lots of work to do, of course. I just wanted to extend my invitation to send patches, if you'd like to do something with tlog.

**Comment by trevor-vaughan** [comment]
Sorry, completely lost this thread for a while.

Basically, with lack of better options, stuffing sudosh2 in front of everyone became the only option. Being..um..more obtrusive, it was a mixed bag.

The crazy back-ends that I'm referring to are custom scripts that would end up parsing the data in elasticsearch and adding additional entries formatted properly for Kibana/Grafana. This would certainly work but would actually create *more* data and duplicate data across the board.

Grafana, by default, doesn't allow you to do queries such as `*`. Instead, you have to know *exactly* what you are looking for. Kibana on the other hand, will allow all of your users to have the ultimate power to query every item in ElasticSearch and potentially bring it to its knees.

We definitely want to see tlog jump into the present as quickly as possible!

**Comment by spbnick** [comment]
Ah, I see, thanks for the explanation, @trevor-vaughan. Our [ViaQ](https://github.com/viaq) project ([talk at DevConf.cz](https://youtu.be/sAhuSXj8nZk?t=3m10s)) is trying to at least do access control in Kibana, perhaps something could be done with that, but I'm not sure. We're considering Grafana too. I'm particularly interested in the possible nested object support for [aushape](https://github.com/Scribery/aushape).

Regarding speeding tlog up, we actually might get some boost in manpower, at least for the playback Web UI this year. Also, my talk at FOSDEM is up, both slides and video: https://fosdem.org/2017/schedule/event/session_recording/

**Comment by frasertweedale** [comment]
I have a (probably crazy) idea for this.

audit log can capture when terminal attributes are set by monitoring for a particular ioctl syscall:

    -a always,exit -F arch=b64 -S ioctl -F a1=0x5403     # 0x5402 = TCSETS
    -a always,exit -F arch=b64 -S ioctl -F a1=0x5403     # 0x5403 = TCSETSW
    -a always,exit -F arch=b64 -S ioctl -F a1=0x5403     # 0x5403 = TCSETSF

Unfortunately the ioctl argument is a `struct termios *` so the audit system only logs a pointer,
not the actual attributes.  Nevertheless we can configure an `audispd` to watch for these events, find a corresponding `tlog` instance and notify it that some terminal attributes were set.

That `tlog` instance can then `tcgetattr` on the master side of the pty to read what the attributes
were and see if the echo mode changed.  Change of echo mode can then be recorded in the "timing" metadata stream, and input characters can be omitted or replaced with placeholders.

As to how the notification occurs, I guess `tlog` can open a unix domain socket named according to the session ID or something like that and `poll` it along with the other fds  This would allow the `audispd` plugin to locate and communicate with the appropriate `tlog` instance.

This is a complex solution and there is more complexity in how to handle situations like input during "echo off" mode being processed before the message that the echo mode *may have* changed is received by `tlog`.  But we would need to determine empirically how likely this is in practice.  It could be mitigated by buffering input for long enough to gain confidence that the echo mode has not changed before committing the input to the log.

**Comment by spbnick** [comment]
Wow, that's crazy indeed :)! I doubt we will use this, but full points on digging this out :)
Another approach could be listening on the audit netlink multicast socket and picking out the event directly from the kernel, but really, I wouldn't like to implement either of these :)

I think in general it would be much easier and more reliable to just disable input recording instead. Input with echo enabled would appear in the output, and the one with echo disabled would be omitted anyway if we implement the "echo off" detection.

**Comment by frasertweedale** [comment]
Yeah I think just output logging covers most of what you want, and I'd put echo mode detection in the "wait and see if anyone *really* needs it" bucket.

**Comment by trevor-vaughan** [comment]
I'm happy with `log: input: false` handling this in the config file.

**Comment by karanb192** [comment]
@frasertweedale , we would also need this feature to avoid logging passwords.

**Comment by spbnick** [comment]
Yep, just disable recording the input, and your passwords (or any input for that matter) won't be recorded, unless they're output by something.
